# This file is generated by optruck.
#   - 1password vault: optruck-development
#   - 1password item: foo
# To restore, run the following command:
#   $ cat .env.1password | grep -v '^#' | op inject > .env
FOO={{op://4ezywiffxaxrqdmnfesfzvizeu/dpbbe4d2du57qfzd4yznon3eny/FOO}}
BAR={{op://4ezywiffxaxrqdmnfesfzvizeu/dpbbe4d2du57qfzd4yznon3eny/BAR}}
