package output

import (
	"os"
	"path/filepath"
	"text/template"

	"github.com/yammerjp/optruck/pkg/op"
)

type EnvTemplateDest struct {
	Path string
}

func (d *EnvTemplateDest) GetPath() string {
	return d.Path
}

func (d *EnvTemplateDest) GetBasename() string {
	return filepath.Base(d.Path)
}

type envTemplateData struct {
	*op.SecretReference
	Dest *EnvTemplateDest
}

func (d *EnvTemplateDest) Write(secretReference *op.SecretReference) error {
	file, err := os.Create(d.Path)
	if err != nil {
		return err
	}
	defer file.Close()

	tmpl, err := template.New("env-template").Parse(`# This file was generated by optruck.{{if .SecretReference.Account}}
#   - 1password account: {{.SecretReference.Account}}{{end}}{{if .SecretReference.VaultName}}
#   - 1password vault: {{.SecretReference.VaultName}}{{end}}
# To restore, run the following command:
#   $ op inject -i {{.Dest.GetBasename}} -o .env{{range .GetFieldRefs}}
{{.Label}}={{.Ref}}{{end}}
`)
	if err != nil {
		return err
	}

	data := &envTemplateData{
		SecretReference: secretReference,
		Dest:            d,
	}
	return tmpl.Execute(file, data)
}
