package output

import (
	"os"
	"path/filepath"
	"text/template"

	"github.com/yammerjp/optruck/pkg/op"
)

type K8sSecretTemplateDest struct {
	Path       string
	Namespace  string
	SecretName string
}

func (d *K8sSecretTemplateDest) GetPath() string {
	return d.Path
}

type k8sTemplateData struct {
	*op.SecretReference
	Dest *K8sSecretTemplateDest
}

func (d *K8sSecretTemplateDest) GetBasename() string {
	return filepath.Base(d.Path)
}

func (d *K8sSecretTemplateDest) Write(secretReference *op.SecretReference) error {
	file, err := os.Create(d.Path)
	if err != nil {
		return err
	}
	defer file.Close()

	tmpl, err := template.New("k8s-secret").Parse(`# This file was generated by optruck.{{if .SecretReference.Account}}
#   - 1password account: {{.SecretReference.Account}}{{end}}{{if .SecretReference.VaultName}}
#   - 1password vault: {{.SecretReference.VaultName}}{{end}}
# To restore, run the following command:
#   $ op inject -i {{.Dest.GetBasename}} {{if .SecretReference.Account}}--account {{.SecretReference.Account}} {{end}}| kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: {{.Dest.SecretName}}
  namespace: {{.Dest.Namespace}}
type: Opaque
data:{{range .SecretReference.GetFieldRefs}}
  {{.Label}}: {{.Ref}}{{end}}
`)
	if err != nil {
		return err
	}

	return tmpl.Execute(file, k8sTemplateData{
		SecretReference: secretReference,
		Dest:            d,
	})
}
